# Generated by Django 3.0.3 on 2020-03-12 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='likedposts',
            name='is_liked',
            field=models.BooleanField(default=True),
        ),
    ]
